title: Roy的笔记
email: xuechengz2022@163.com
description: Roy的笔记
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: roy2xc # add your name
author-pic: chzng-face.jpg
about-author: My name is Roy2xc, I'm now a C++ programer, and I will be a full time 3D reconstruction Engineer.

# Contact links
email: xuechengz2022@163.com # Add your Email address
phone: none # Add your Phone number
website: https://roy2xc.github.io/ # Add your website, do not add http://
github: Roy2xc # Add your Github handle
twitter: no twiteer # Add your Twitter handle

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
